todo-app.Mvc/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using todo_app.Domain;
using todo_app.Domain.DTOs;
using todo_app.Domain.ViewModels;
using todo_app.Mvc.Models.Repository;

namespace todo_app.Mvc.Controllers
{
    [Route("[controller]")]
    public class TodoController : Controller
    {
        private readonly ITodoRepository todoRepository;

        public TodoController(ITodoRepository todoRepository)
        {
            this.todoRepository = todoRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var todos = this.todoRepository.SelectAll();
            ViewBag.today = DateTime.Today;
            ViewBag.tomorrow = DateTime.Today.AddDays(1);

            return View(todos.ToList());
        }

        [HttpGet("filter")]
        public async Task<IActionResult> FilterTodos([FromQuery] string dueDate)
        {
            var todos = this.todoRepository.SelectAll();

            if (dueDate == "today")
            {
                var todayStart = DateTime.Today;
                var todayEnd = todayStart.AddDays(1);

                var todosDueToday = this.todoRepository.SelectAll()
                    .Where(t => t.DueTime >= todayStart && t.DueTime < todayEnd)
                    .ToList();

                return View(todosDueToday);
            }

            var emptyList = Enumerable.Empty<Todo>().ToList();

            return View(emptyList);
        }

        [HttpGet("[action]")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[action]")]
        public async Task<IActionResult> Create([FromForm] TodoCreateDto createDto)
        {
            try
            {
                if (createDto.DueTime < DateTime.Now)
                {
                    ModelState.AddModelError("DueTime", "Please select an upcoming date");
                }

                if (ModelState.IsValid)
                {
                    var todo = new Todo
                    {
                        Id = Guid.NewGuid(),
                        Title = createDto.Title,
                        Description = createDto.Description,
                        DueTime = createDto.DueTime,
                        CreatedAt = DateTime.UtcNow,
                        Status = TodoStatus.NotStarted
                    };

                    Todo entity = await this.todoRepository.AddAsync(todo);

                    return RedirectToAction("Index");
                }

                throw new ArgumentException("Invalid parameters");
            }
            catch (ArgumentException ex)
            {
                return View("Create", createDto);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpGet("[action]/{id}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            try
            {
                if (id == Guid.Empty)
                {
                    throw new ArgumentException("Invalid id");
                }

                Todo todo = await this.todoRepository.SeclectByIdAsync(id);

                if (todo is null)
                {
                    return NotFound();
                }

                return View(todo);
            }
            catch (ArgumentException ex)
            {
                return View("Error");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[action]/{id}")]
        public async Task<IActionResult> Edit([FromForm] Todo todo)
        {
            try
            {
                if (todo.DueTime < DateTime.Now)
                {
                    ModelState.AddModelError("DueTime", "Please select an upcoming date");
                }

                if (ModelState.IsValid)
                {
                    Todo UpdatedTodo = await this.todoRepository.UpdateAync(todo);

                    return RedirectToAction("Index");
                }

                throw new ArgumentException("Invalid parameters");
            }
            catch (ArgumentException ex) 
            {
                return View("Edit", todo);
            }
            catch (Exception ex)
            {

                return View("Error");
            }
        }

        [HttpPost("[action]/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Todo retrivedTodo = await this.todoRepository.SeclectByIdAsync(id);

                    if (retrivedTodo is null)
                    {
                        return NotFound();
                    }

                    Todo todo = await this.todoRepository.DeleteAsync(retrivedTodo);

                    return RedirectToAction("Index");
                }

                throw new ArgumentException("Invalid parameters");
            }
            catch(ArgumentException ex)
            {
                return View("Error");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[action]")]
        public async Task<IActionResult> ChangeStatus([FromQuery] Guid id, [FromQuery] TodoStatus status)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    Todo todo = await this.todoRepository.SeclectByIdAsync(id);
                    todo.Status = status;

                    var updatedTodo = await this.todoRepository.UpdateAync(todo);

                    return RedirectToAction("Index");
                }

                throw new ArgumentException("Invalid id or status");
            }
            catch(ArgumentException ex)
            {
                return View("Error");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
    }
}

todo-app.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/todo_app.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Todo App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Todo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>